[package]
name = "fast_deltas_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["cargo"] }
xz = "0.1.0"
fast_deltas = {path = "../../fast_deltas"}
